### ISSUE TITLE
ACT_AS_USER scope

### ISSUE THREAD

**Issue by zhil** [thecatontheflat/atlassian-connect-bundle#15]
Atlassian added pretty cool feature, [ACT_AS_USER](https://developer.atlassian.com/blog/2016/10/Atlassian-Connect-now-allows-Add-ons-to-make-requests-on-behalf-of-a-user/)

From [what I see](https://developer.atlassian.com/static/connect/docs/latest/concepts/OAuth2-JWT-Bearer-Token-Authentication.html), this feature would require this bundle changes.

@thecatontheflat 
It looks like good improvement for your toggl plugin (plugin will be able to submit time for users in background), will you be interested in adding ACT_AS_USER to this bundle?

**Comment by thecatontheflat** [comment]
Toggl Integration Add-On submits the data from the client side using `AC` JS library, so the data is signed on behalf of the user.

However, adding `ACT_AS_USER` feature to this bundle would be awesome (as long as it is optional or something in the bundle configuration).

**Comment by zhil** [comment]
@thecatontheflat you could use that in order to integrate toggl hooks. So, whenever user will add timeentry using desktop app - it could be automatically added to Jira

**Comment by thecatontheflat** [comment]
Thanks for the suggestion! There is a logic for this case already. I am using nodejs for that project 😸

**Comment by zhil** [comment]
@thecatontheflat 
well, as I remember, user was required to map their toogl entries on special page, if they track time using desktop client.
with this feature you will be able to link worklogs automatically, if user enter issue ID in toggle client.

**Comment by thecatontheflat** [comment]
Yeah I get that 😄  That project uses nodejs anyway, with atlassian-connect-express framework.

**Comment by zhil** [comment]
Sorry for anoying, so I can act as other user from server side code using nodejs snd and  atlassian-connect-express ? I need it in my plugin, so looking for solution

**Comment by thecatontheflat** [comment]
Yeah, according to the docs ACE supports acting on behalf of the user (although I am not using this feature so I cannot say anything about its reliability):

https://bitbucket.org/atlassian/atlassian-connect-express
Search for `asUser` on the page

**Comment by Bukashk0zzz** [comment]
Add this feature in 2.3 https://github.com/thecatontheflat/atlassian-connect-bundle/releases/tag/2.3.0
Now using Rest client you can set user id and send requests from it.
