### ISSUE TITLE
Configure SensioLabs checker

### ISSUE THREAD

**Issue by thecatontheflat** [thecatontheflat/atlassian-connect-bundle#28]
@Bukashk0zzz It seems to work (the badge appears on the readme), but for some reason it does not show up in the PR. Can it be project configuration issue?

**Comment by Bukashk0zzz** [comment]
As you can see here https://github.com/Bukashk0zzz/LiipImagineSerializationBundle

I have same badge at readme. And there're no any additional config for it.

Project config:
<img width="1067" alt="screen shot 2017-12-22 at 12 02 51" src="https://user-images.githubusercontent.com/1908342/34294189-0eac7a76-e710-11e7-93b5-4c6a978dfb42.png">

**Comment by Bukashk0zzz** [comment]
Maybe if nothing helps. Just remove project. and add one more time.
