### ISSUE TITLE
Error installing the bundle on Symfony 4.2 with Flex

### ISSUE THREAD

**Issue by jorgesb** [thecatontheflat/atlassian-connect-bundle#40]
Hi @thecatontheflat, 
I've installed this bundle on Symfony 4.2 with flex by composer. It throws the following error:
[KO]
Script cache:clear returned with error code 1
!!  
!!  In AtlassianConnectExtension.php line 26:
!!                                   
!!    Notice: Undefined index: prod

![image](https://user-images.githubusercontent.com/1453104/62208229-82a79d80-b396-11e9-8e32-cc79c06a5949.png)

I guess I should change the configuration, but it looks weird that just installing it throws an error.

Is it prepared to work with Symfony 4.2 with Flex?

Thanks in advance!

**Comment by Bukashk0zzz** [comment]
Hi,

Before install composer dependency you need to create config from step 3:

https://github.com/thecatontheflat/atlassian-connect-bundle#step-3-bundle-configuration

**Comment by jorgesb** [comment]
Hi @Bukashk0zzz ,

thanks for your answer. There isn't a config.yml file on Symfony 4. Where is the proper place to add that config then?

Beside that, I would change the steps order on the readme file to avoid that error.

**Comment by Bukashk0zzz** [comment]
Create file config/packages/atlassian_connect_bundle.yaml and put there config from step 3.

In readme we have only description how to install bundle without Symfony flex.

**Comment by jorgesb** [comment]
Ok understood.

Thanks!

**Comment by Matth--** [comment]
I assume this ticket is resolved due to it's age.
