### ISSUE TITLE
Missing documentation about authentication and scope

### ISSUE THREAD

**Issue by andrejsstepanovs** [thecatontheflat/atlassian-connect-bundle#43]
I'm trying to install this app and I'm getting this error on jira side.

```
The app descriptor failed to validate against the schema. Please confirm this app is intended for use with JIRA and then contact the app vendor.
  : object has missing required properties (["authentication"])
```

I know that I can get this error go away by setting:
```
atlassian_connect:
    prod:
        authentication:
            type: none
```

Then installation works but I'm not getting tenant `oauth_client_id` and `shared_secret`.

If I set `type: jwt` then I get `shared_secret`. But still no `oauth_client_id`.

Now I figured to get `oauth_client_id` I need to request specific scopes: 
```
    scopes: ['READ', 'WRITE', 'ACT_AS_USER']
```

So all is working just missing documentation. Please add to docs that

- to get `oauth_client_id` need to add `scope`
- `authentication` needs to be set so installation will work and maybe set it to `jwt` as default

**Comment by Bukashk0zzz** [comment]
Thanks a lot for this. I will add it to README
