### ISSUE TITLE
Branch strategy and Symfony compatibility

### ISSUE THREAD

**Issue by Matth--** [thecatontheflat/atlassian-connect-bundle#54]
More of a question/suggestion

Could we have a `3.x` branch with the current release and then a 4.x branch where we only allow PHP: ^8.0. (symfony 6 is 8 and up)

**Comment by Bukashk0zzz** [comment]
I am not sure that's is necessary. We can just drop compatibility for the new version and that it. 
But creating 3.x branch and leaving it as is for backup is a good idea.
