### ISSUE TITLE
Easy extend

### ISSUE THREAD

**Issue by zhil** [thecatontheflat/atlassian-connect-bundle#9]
It would be nice to rebuild plugin like https://sonata-project.org/bundles/easy-extends/2-x/doc/reference/why.html So tenant entity could be easily extended.

It may break bc though.

**Comment by zhil** [comment]
@thecatontheflat what do you think about this issue?

**Comment by thecatontheflat** [comment]
That sounds like a right thing to do. We can just create a major tag and forget about BC.

**Comment by zhil** [comment]
@thecatontheflat 
right now I miss ability to add new properties to Tenant entity. EastExtends looks like over-complication, what do you think, if I will add parameter, which will allow to override Tenant entity?
We will be able to inherit Tenant entity in AppBundle/Entity/Tenant and add properties in it?
It would be BC compatible and pretty simply to use.

**Comment by thecatontheflat** [comment]
Do you mean a parameter with the class name, which can be changed to some local class? Yes, that is a good solution

**Comment by zhil** [comment]
@thecatontheflat ok, added PR #16

**Comment by thecatontheflat** [comment]
Merged! 🥇
